### ISSUE TITLE
为什么image的维度是[batch_size,28,28]

### ISSUE THREAD

**Issue by li-xin-yi** [gantheory/TPA-LSTM#4]
https://github.com/gantheory/TPA-LSTM/blob/598cfc90f778856084f0ca80b463894e7ea26481/lib/data_generator.py#L37

我没有在论文中找到解释

**Comment by sturbon** [comment]
Downloading muse dataset from Google drive...
Traceback (most recent call last):
  File "C:\conda\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\conda\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\conda\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\conda\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\conda\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\conda\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\conda\lib\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "C:\conda\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000294198976A0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\conda\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\conda\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\conda\lib\site-packages\urllib3\util\retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1a5361IfxxEY1mmTfqAviiIkq6u2OYFJ7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000294198976A0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/github 论文/TPA-LSTM-master/main.py", line 35, in <module>
    main()
  File "F:/github 论文/TPA-LSTM-master/main.py", line 14, in main
    graph, model, data_generator = create_graph(para)
  File "F:\github 论文\TPA-LSTM-master\lib\model_utils.py", line 28, in create_graph
    data_generator = create_data_generator(para)
  File "F:\github 论文\TPA-LSTM-master\lib\model_utils.py", line 15, in create_data_generator
    return MuseDataGenerator(para)
  File "F:\github 论文\TPA-LSTM-master\lib\data_generator.py", line 286, in __init__
    self._download_file()
  File "F:\github 论文\TPA-LSTM-master\lib\data_generator.py", line 120, in _download_file
    download_file_from_google_drive(self.DATASET_ID,
  File "F:\github 论文\TPA-LSTM-master\lib\utils.py", line 54, in download_file_from_google_drive
    response = session.get(URL, params={'id': id}, stream=True)
  File "C:\conda\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "C:\conda\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\conda\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\conda\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1a5361IfxxEY1mmTfqAviiIkq6u2OYFJ7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000294198976A0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

Process finished with exit code 1

**Comment by w81192** [comment]
> https://github.com/gantheory/TPA-LSTM/blob/598cfc90f778856084f0ca80b463894e7ea26481/lib/data_generator.py#L37
> 
> 我没有在论文中找到解释

那个数据和论文没有直接关系，看起来是其他地方的代码，只不过在这里用了一下这个函数
